---
title: "Reporting practices"
author:
  - name: "Joe Warne¹"
  - name: "Jennifer Murphy¹"
  - name: "Daniël Lakens²"
  - name: "Cristian Mesquida²"
format: docx
knitr:
  opts_chunk:
    echo: false
# bibliography: references.bib
# csl: 
editor: visual
---

#### Affiliation

¹ School of Biological, Health and Sports Sciences, Technological University Dublin, Tallaght, Dublin, Ireland

² Human-Technology Interaction Group, Eindhoven University of Technology, Eindhoven, The Netherlands

#### ORCIDs

Joe Warne – 0000-0002-4359-8132

Jennifer Murphy – 0000-0001-8624-3828

Daniël Lakens – 0000-0002-0247-239X

Cristian Mesquida – 0000-0002-1542-8355

#### Correspondence

Joe Warne - joe.warne\@tudublin.ie, www.ssreplicationcentre.com

**Data availability**

The preregistration, data and analysis scripts related to this study are publicly available on the Open Science Framework and can be found at https://osf.io/3juyq/.

**Disclosure statement**

Cristian Mesquida, Jennifer Murphy, Joe Warne and Daniël Lakens declare that they have no conflict of interest.

**Funding**

Cristian Mesquida was supported by the Ammodo Science Award 2023 for Social Sciences.

\pagebreak

```         
{r}
library(metacheck) 
library(dplyr) 
library(readxl)
library(here)
library(rlang)
library(purrr)
library(tidyr)
library(statcheck)
library(stringr)
library(tibble)
library(readr)
```

# Introduction

Most findings in the field of sport and exercise science are based on the results of null hypothesis significance testing (NHST). It is therefore important that NHST is performed correctly and that statistical results are reported accurately and completely. However, there is evidence from other fields, such as psychology, that reported *p*-values do not match the test statistic and degrees of freedom from which they are derived (Bakker & Wicherts, 2011; Nuijten et al., 2016; Veldkamp et al., 2014). For instance, Nuijten et al., (2016) found that about half of screened published psychology articles using NHST contained at least one inconsistent *p*-value. This could be sloppy reporting (e,g., p \< 0.3 when p = 0.305, or p = .000 when p-values can never be 0) but may also reflect an inconsistent claim where the reported *p*-value is significant (p \< .05) and the computed *p*-value was not (p \> 0.05), or vice-versa. Issues such as these may suggest human error, but also opportunistic misreporting of statistical results. It is impossible to evaluate the consistency of *p*-values in the absence of either raw data, or fully reported test statistics and degrees of freedom. When statistical tests are reported completely, data can be checked in the form of p-value reproducibility checks, which increase the transparency and validity of published research. Therefore, the full reporting of parameters associated with statistical tests is good practice, and should be adopted by researchers and enforced by journals.

In addition to reporting critical test statistics for NHST, there are increased calls for the improved reporting of associated effect sizes (e.g. Lakens). In addition to the value of the effect size in the practical interpretation of claims, effect sizes also facilitate meta-analyses and pre-study power calculations. However, the common reporting of only point estimates for effect sizes does not allow researchers to assess the uncertainty around these estimates, which requires confidence intervals. A further benefit of reporting confidence intervals around effect sizes is that they facilitate principled evaluation of replication results, not by assessing overlap between confidence intervals, but by allowing researchers to determine which effect sizes are compatible with the data and which can be rejected (Lakens, 2022 - https://lakens.github.io/statistical_inferences/17-replication.html#analyzing-replication-studies). In particular, confidence intervals can be used to assess whether theoretically or practically meaningful effect sizes can be ruled out, for example through equivalence testing, even when such tests were not originally conducted. Therefore, beyond test statistics, degrees of freedom and absolute *p*-values, studies should also report effect sizes and their confidence intervals. Such recommendations are common in other fields, and are for instance part of the Journal Article Reporting Standards of the American Psychological Association (<https://doi.org/10.1037/amp0000191>).

Comprehensive and accurate reporting of all statistical information should be common practice in the scientific literature. However, this issue would be less problematic if researchers routinely shared raw data along with their methods. Providing raw data improves the reproducibility of reported claims and facilitates data re-use across a range of different contexts, including future meta-analyses, meta-syntheses (e.g., z-curve), model validation, and replication studies. Despite these benefits, data sharing remains rare in sports and exercise Science (SES). For example, Twomey found that only 0.67% of 300 articles \[95% CI: 0.08 to 2.39%\] reported a statement for data sharing or open data. Similarly, Borget al. (2020) reported that only 4.3% of 299 articles \[95% CI: 2.3 to 7.3%\] from quartile 1 SES journals shared their data and/or code. A case study in the Journal of Sports Sciences also reported that 0% of 174 articles shared their data (Mesquida). Finally, colleagues in Exercise Medicine recently reported very poor access to previously collected data to validate a model for predicting gestational diabetes, even after directly contacting authors who had data-sharing statements in their publications (GERMAINE). Therefore, poor data sharing presents a significant barrier to replication and reproducibility checks, in addition to limiting the validation of models of the future.

Without access to statistical data, combined with the absence of raw data or analysis code, it is impossible to comprehensively identify errors, or re-use data, thereby hindering cumulative science (Errington et al., 2017; Nuijten et al., 2016, add [https://doi.org/10.1037/a0015972](https://psycnet.apa.org/doi/10.1037/a0015972) ). Contrarily, when statistical data are fully reported, researchers can verify the reported results, which strengthens their credibility and allows researchers to re-use such data to better inform future research. The aim of the current study is to 1) describe the reporting practices of NHST statistical results for the main effect of interest in 10 quartile 1 applied SES journals, and 2) assess the reproducibility of *p*-values in the cases where sufficient statistical information is presented. As the lack of a complete reporting of statistical results can be compensated by making raw data publicly available, we also aim to 3)report the proportion of studies that make raw data publicly available on a data repository. Our study is intended to be an exploratory, descriptive report and therefore no hypotheses will be tested.

Although the preregistered protocol specified coding only the primary statistical result from each study, this decision reflected feasibility constraints. After manuscript completion, members of the team developed *meta-check*, an automated tool capable of extracting all reported statistical tests within an article, in addition to being able to *statcheck* these mass results. This advance enabled a more comprehensive assessment of reporting practices across the same set of studies (n = 350), without changing the study sample, inclusion criteria, or core research questions and we made the decision to retrospectively add the analysis here. The expanded analysis was motivated by improved measurement coverage rather than the observed results, and reduces potential bias associated with focusing on a single result per study. In line with transparent research practices, this deviation from the preregistered plan is explicitly documented and reported alongside the preregistered analysis.

# Methods

This is a retrospective observational study. The preregistration of this study can be found at https://osf.io/3juyq/.

**Study sample size**

A sample of 350 studies was used for the purpose of this study. As stated in the preregistration, this sample size was based on a precision analysis conducted for a previous study to find an expected proportion of 30% of studies reporting an a priori power analysis (<https://osf.io/mqbr2/>). To find a proportion of 30% with a margin of error of 5%, the precision analysis returned a sample of 323 studies, which was rounded up to 350 studies. These 350 studies were used to conduct the current report.

**Journal and study selection protocol**

The 350 studies were sampled from 10 journals ranked in quartile 1 according to www.scimagojr.com (as of 13th September, 2022). The list of journals can be found at <https://osf.io/d7wyc/>. The study selection protocol was based on the *Selection Protocol for Replication in Sports and Exercise Science* (Murphy et al., 2022). Only applied sport and exercise science studies in the subdisciplines of physiology, sports performance, physical activity, injury prevention and psychology were considered. By applied sport and exercise science studies we refer to the study of changes in human performance in response to physical activity, exercise, and sport. Thus, we excluded reviews of any type (e.g., systematic, narrative, scoping and educational), meta-analysis, consensus statements, opinion pieces or commentaries, editorials, case studies, conference proceedings, study protocols, perspectives, and methodological reports. Moreover, only confirmatory studies were considered. By confirmatory we refer to any study that tests a hypothesis with an experimental or quasi-experimental design. A quasi-experimental design was defined as an empirical study used to estimate the causal impact of an independent variable on target population without randomization. Furthermore, only studies which contained hypothesis tests using *t*-test and *F*-tests were included. For *F*-tests, both main effects and interaction effects were considered. Statistical results from *post-hoc* tests were only considered if the corresponding prediction is stated in the hypothesis, otherwise we report the main effect or interaction only.

Although we attempted to apply the protocol described in Murphy et al., (2022) to select studies, we deviated on two points from the original protocol. First, while the *Selection Protocol for Replication in Sports and Exercise* only selected studies that reported a statistically significant main effect, we considered both statistically significant and nonsignificant effects. Second, we also considered interaction effects as opposed to the original selection protocol.

**Inter-rater reliability**

```{r}
Insert inter rate code here
```

Prior to collecting any data, and in anticipation of difficulties to select the statistical result central to the tested hypothesis, we developed coding strategy over a 4-step process. First, the four authors (CM, JM, DL and JW) developed and discussed the coding form created by CM. Ambiguities in the coding form were discussed, and amendments were made. Second, three raters (CM, JM and JW) independently coded a randomly selected subset of 28 studies from the sample pool of studies (350) as a pilot study. Subsequently, raters’ responses were compared, and any disagreements were used to improve the clarity of coding form. Third, the same three raters (CM, JM and JW) independently coded a second random subset of 19 studies. Interrater agreement was assessed by calculating a pooled Fleiss’ Kappa estimate for each coding category across the 47 studies coded in the first two rounds of coding. The mean interrater agreement for the categorical responses was 0.61, indicating substantial agreement. The second round of coding was also used to discuss disagreements. The remaining 303 studies were double coded whereby both JM and JW each coded \~176 studies and CM coded the full sample of studies (350). Interrater agreement was assessed by calculating a pooled Cohen’s Kappa estimate. The interrater agreement for the final round of coding was 0.84, indicating almost perfect agreement. Interrater agreements across variables and the coding form can be found at https://osf.io/3juyq/.. After termination of data collection, any discrepancies in coding decisions were resolved through discussion between the two pairs of raters and can be found at  https://osf.io/3juyq/. DL provided guidance when discrepancies arose and agreement between two raters could not be reached.

**Procedures and data extraction**

Only one *p*-value per study was extracted, which corresponded to the main statistical test for the central hypothesis of each study. Because hypotheses statements often include vague language and the primary dependent variable is not always operationalized clearly, we used a coding strategy that consisted of several steps to select the key dependent variable. First, the selected dependent variable would be the one for which researchers controlled both type I and type II error rates. Specifically, in addition to controlling for type I error, researchers conducted an a priori power analysis to control for type II error. Thus, the key dependent variable should be listed in both the a priori power analysis and hypothesis statements. However, on some occasions the dependent variable stated in the a priori power analysis would not match the dependent variable stated in the hypothesis. In these cases, we would select the dependent variable stated in the hypothesis, if clearly identifiable. Often, the statistical result central to the hypothesis tested was difficult to identify due to the lack of a priori power analysis and vagueness of the hypothesis tested. This included hypothesis statements that predicted the effect of one or several interventions on more than one dependent variable or a dependent variable that was measured in multiple ways. In those cases, we selected a dependent variable linked to the central hypothesis test and listed in: 1) the sentence describing the aim of the study; 2) the abstract; 3) title; 4) or the results, in this order of priority. We selected the dependent variable that best matched the language the authors use to imply the focus of the study, in cases where there were still several dependent variables listed.

For the present study, we coded the main selected test of interest, the statistical result of interest (i.e., *F*-test or *t*-test, degrees of freedom, *p*-value, effect size (both standardized and unstandardized) and confidence interval for the effect size of interest). Secondly, we coded if each study has been preregistered, shares raw data, and if that data is accessible using the link provided (See Table 1 for coding strategy).

**Table 1**: Coding strategy specific to this study.

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| Item                                                                                                                                                                             | Action                                                                                  |
+==================================================================================================================================================================================+=========================================================================================+
| 1.  Primary hypothesis quote                                                                                                                                                     | Copy pasted quote of the primary or otherwise first listed hypothesis statement         |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 2.  Based on the primary hypothesis, what is the key statistical result?                                                                                                         | Select from a list (*differences of means, main effect,* *interaction effect, unclear*) |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 3.  Statistical result quote                                                                                                                                                     | Copy pasted quote of the statistical result of interest based on the effect of interest |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 4.  If the key statistical test is an *F*-test:                                                                                                                                  | a\) Report both the numerator and denominator degrees of freedom                        |
|                                                                                                                                                                                  |                                                                                         |
|                                                                                                                                                                                  | b\) Report the *F*-ratio                                                                |
|                                                                                                                                                                                  |                                                                                         |
|                                                                                                                                                                                  | c\) Report the *p*-value                                                                |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 5.  If the key statistical test is a *t*-test:                                                                                                                                   | a\) Report the degrees of freedom                                                       |
|                                                                                                                                                                                  |                                                                                         |
|                                                                                                                                                                                  | b\) Report the *t*-statistic                                                            |
|                                                                                                                                                                                  |                                                                                         |
|                                                                                                                                                                                  | c\) Report the *p*-value                                                                |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 6.  Is the effect size standardised or unstandardised? *Unstandardised effects include raw mean differences, standardised effects include any normalised d or r family of tests* | Select from a list (*standardized,                                                      |
|                                                                                                                                                                                  | unstandardized, both* and *not reported*)                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 7.  Is the confidence interval for the effect size of interest reported? *This includes both the standardised or unstandardised effects*                                         | Select from a list (*yes*/*no*)                                                         |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 8.  Has the study been preregistered?                                                                                                                                            | Select from a list (*yes*/*no*)                                                         |
|                                                                                                                                                                                  | and indicate if this is a clinical trial registration or not.                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 9.  Does the study provide a link to a data repository where the raw data is publicly available?                                                                                 | Select from a list (*yes*/*no*)                                                         |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+
| 10. If the study provides a link to a data repository, does the link work and the study data is available?                                                                       | Select from a list (*yes*/*no*)                                                         |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+

: *Note that this coding strategy deviates slightly from the pre-registration in that we no longer code the key statistical test type (e.g. paired t-test, 1-way ANOVA etc) as specified in item 4 of the preregistration. This decision was made because this information did not inform our analysis and we already include the number of t and F tests.*

**1.1.  Statistical analysis**

All research data and analysis syntax can be found at https://osf.io/3juyq/.

To evaluate the prevalence of reporting errors, the R (R Core Team,2019 Ver:) package *statcheck* (Epskamp & Nuijten, 2018*)* was implemented to recompute *p*-values based on reported test statistics and their degrees of freedom, that were re-formatted into a standardized APA format following coding. If the degrees of freedom (Df) were not reported for a test, but the F or t value were included, we attempted to infer these values from the study design. For reproducibility, we include a link to the Excel calculator on the OSF page. Two authors (J.W and C.M) estimated the degrees of freedom for missing data independently. If there was a disagreement, both results were tested for reproducibility, and authors were given the benefit of the doubt.

We compared the reported and recalculated *p*-value and report the result as:

\- ***Reproduced*****:** if the reported *p*-value matches the recomputed *p*-value. We rounded up or down the recomputed *p*-value to 2 decimals to see whether it matches the reported *p*-value. For instance, in the case that the recomputed *p*-value is 0.034 and the reported *p*-value has been rounded to 0.03, we  considered it had been *reproduced*.

\- ***Not reproduced but compatible*****:** if the original *p*-value had been reported as *p* \< 0.05 or *p* \> 0.05 and the recomputed *p*-value is compatible with the (non)significance of the reported *p*-value. For instance, an original *p*-value is reported as anything less than *p* \< 0.05  was considered *not reproduced but compatible* if the recomputed *p*-value reaches statistically significance. The same will apply to a nonsignificant *p*-values (*p* \> 0.05). [\[DL1**\]**](#_msoanchor_1)**I would also report how often there were imprecise p-values reported. Best practice, and JARS, is to report exact p-values. How often did they not do this? Papercheck can automatically  check this for all papers.**

\- ***Incorrectly rounded***: if the recomputed *p*-value differed from the reported *p*-value after rounding off the *p*-value by a decimal place. For instance, if the recomputed *p*-value is 0.038 but it has been reported as 0.03, we considered it as incorrectly rounded. Another example could be if the original *p*-value is reported as *p* \< 0.01 but the recomputed *p*-value was 0.015[\[DL3\]](#0) .

\- ***Incompatible*****:** if the reported *p*-value was equal to or smaller than the type I error rate (typically 0.05) but the recomputed *p*-value was larger than the type I error rate, or vice versa. As this changed the statistical conclusion, the reported p-value is considered incompatible with the reproduced p-value. For instance, if the recomputed *p*-value is 0.058 but it has been reported as *p* = 0.05 (or *p* \< 0.05) and the study claims that statistical significance has been reached, we will consider it as *incompatible*.

[As described in the introduction, we also retrospectively utilized meta-check (VER) to more comprehensively evaluate the reporting practices and statcheck the entire sample. The full complement of 347 studies were converted to .XML before the modules X, X, and X were run.]{.underline}

# Results

**Results part 1 - Original study outcomes**

For 7 of the 350 studies we could not determine what the main statistical test was, and these studies were not grouped into either the F test or t test categories for reproducibility checks.

Aim 1: With respect to the reporting practices, whilst 95% of studies (N=331) reported a *p*-value for the main effect of interest, only 40% (N = 139) reported the test statistics (F or t), 29% (N=101) reported the degrees of freedom, 54% (N=188) reported an estimate of effect size, and 8% (N=27) reported the confidence interval of the effect. With respect to the effect size reported, 4% (N=14) report both a standardized and unstandardized effect size, 2% (N=6) report only an unstandardized effect size, and 48% (N=168) reported a standardized effect size. **\[INCLUDE IN TABLE\]**

Aim 2: 66% (N=232) of studies reported an F test as the main effect of interest (Interaction effect N = 119, Main effect N = 113). We were able to determine the degrees of freedom for 31 studies. We were able to generate a *statcheck* report for 51% (N=119) of these studies. Of these, 66% (N=79) were directly reproduced, 27% (N=32) were not reproducible but compatible, and 6% (N=7) studies were incorrectly rounded.  Only 2 studies were incompatible.

32% (N=111) of studies reported a difference in means as the main effect of interest. We were able to determine the degrees of freedom for 4 of these studies, and were thus able to generate a *statcheck* report for only 12% (N=13) of these studies, of which 12 were directly reproduced and 1[\[DL3\]](#_msocom_3)  incorrectly rounded.

Aim 3: Finally, we observed that only 2% (N=6) studies included a data sharing link, and we confirmed that all links led to data files that we could access. **\[NEED TO REBUT CRIS AND DANIEL HERE\< AS THIS WAS IN THE PRE_REG - so keep\]**

**[\[DL3\]](#_msoanchor_3)Add percentages, it is only 1, but also 1/13.**

**Results part 2 - Metacheck report including all statistical results reported in the 350 studies**

# Discussion

The implications of these findings are important for our discipline, a field heavily reliant on statistical inference via null hypothesis significance tests (NHST). First, accurate reporting of inferential statistics is foundational to the interpretation and reuse of findings. Inadequate reporting of test statistics, degrees of freedom, and confidence intervals undermines reproducibility and limits the scope for verification (Nuijten et al., 2016; Errington et al., 2021). Moreover, without standardized effect sizes and intervals of uncertainty, it is nearly impossible to assess the magnitude and precision of effects, impeding efforts to evaluate practical relevance or aggregate data across studies. There appears to be a deficit in the awareness of researchers, peer reviewers and journals as to why the reporting of this information is so important for cumulative science. **DANIEL - This is a fine start for the discussion, and then I would add that the large percentages of missing information threaten the cumuluative character of the science.**

Second, the near absence of data sharing signals a critical absence of transparency in the research method of our field. This has been observed previously, when Twomey et al. previously found that just 0.67% of SES studies shared data, and our previous work identified a 0% data sharing rate (Mesquida) - figures essentially replicated in this sample. Further, Borg *et al.* (2020) found that only 4.3% shared their data and/or code in a comparable audit. These findings are similar to some other fields, such as biomedical sciences (Germaine et al., 2023), but much lower than other fields, such as economics, and psychology (<https://doi.org/10.1038/s41467-023-41111-1>). Whilst there are valid cases in which data cannot be shared, such as personal medical data, authors still have options to protect privacy without sacrificing transparency. One approach is the use of synthetic data, which allows researchers to simulate datasets in ways that control the degrees of resemblance to the original data while limiting the disclosure of informative information (XXX for data protection \[borg paper\] and synthetic data - Also add a reference to synthetic data <https://www.nature.com/articles/s41746-023-00927-3>). However, we do believe that this sensitive data represents the minority of SES research and instead the lack of data sharing represents a systemic lack of transparency and openness to falsification in our field. Finally, the lack of data sharing raises concerns about selective reporting, and p-hacking (Wicherts et al., 2011; Open Science Collaboration, 2015) which should be investigated further given the presence of publication bias in our published literature (Mesquida JSS/ Borg). In order for the sharing of code and data to become a normal part of the scientific process, there needs to be a culture shift toward self-correction and a normalization of scientific errors (Brown *et al.*, 2018). There is an important role for journals here to raise the bar in transparency, and data and code sharing - when ethically possible - should become the default in all high-quality journals in our field.

Despite a successful reproducibility check of the 132 studies for which it was possible, the limitations of the sample must be acknowledged. Just over one-third of studies provided sufficient information for p-value reproducibility checks, and 35 of those still required us to manually determine the degrees of freedom. Hence, it remains uncertain whether the low error rate in the reproducible subset generalizes to the full population. We also cannot evaluate if the studies that do report all critical test statistics are more reproducible than those that do not report these metrics, although Wicherts and colleagues (2011) suggested the lack of data sharing was  associated with weaker evidence, as well as a higher proportion of statistical reporting errors, in 1148 results across 49 research papers in psychology (doi:10.1371/journal.pone.0026828).  

A further limitation was that whilst the coding protocol was carefully piloted and interrater reliability was addressed, some degree of subjectivity in identifying the primary statistical test of interest is unavoidable, especially given inconsistent or vague hypothesis statements. It may also have been possible that there were multiple tests of interest within a paper, and our method of only selecting one may be considered a limitation to the generalizability of these results. Third, the reproducibility analysis relied on the “statcheck” package, which is limited to APA-formatted Fand t tests. Thus, studies using regression models, nonparametric tests, or other incompatible analyses were excluded for feasibility.

In order to improve our research reporting in the future, we suggest the following:

·       **Mandatory Reporting Guidelines:** Journals should enforce the use of standardized statistical reporting checklists, such as those recommended by the APA. All inferential statistics should include test statistics, degrees of freedom, exact p-values, [(un)]{.underline}standardized effect sizes, and 95% confidence intervals of the effect size.

·       **Data Sharing and Open Materials:** Authors should deposit raw data and analysis scripts in public repositories (e.g., OSF,[figshare, Zenodo]{.underline}~~AsPredicted~~) as a condition for publication. Reviewers and editors should verify that links are active and that the materials correspond to reported results. **CRIS - Should we elaborate this a bit more? That is, discuss/mention best practices when sharing data such as including a readme file, codebook, data in a machine-readable format, structure of the repository, etc.**

·       **Statistical Education:** Improved training for researchers and students on good statistical practice, including the use of reproducibility tools (e.g., statcheck, statreport), may reduce reporting errors and increase awareness of transparency standards.

This study offers a description of sub-optimal statistical reporting and reproducibility practices in applied SES journals. While outright errors that reverse statistical conclusions seemed to be rare, the field is marked by widespread underreporting of critical statistical information and near-total absence of data sharing. These findings point to a persistent gap between best-practice recommendations and everyday research conduct. Encouragingly, when statistical data are reported, p-values are largely reproducible. However, this is no cause for complacency. Without broader adoption of transparency measures - including full statistical reporting and the sharing of open data and analysis syntax, the field risks losing trust in its empirical foundations. Addressing these issues will require coordinated efforts across researchers, journals, funders, and institutions. We offer some suggestions for this, and if SES is to mature into a fully cumulative and self-correcting science, researchers must embrace open science as not merely an ideal but a professional obligation. The “reproducibility crisis”, while challenging, offers an unprecedented opportunity to reshape the standards of scientific integrity and accelerate the changed required to build a robust scientific culture.

# References